### ISSUE TITLE
Could you kindly release the processed data

### ISSUE THREAD

**Issue by HantaoShu** [vamships/PECAN#1]
Hi Srivamshi Pittala,
I'm quite interested in this paper, could you kindly release the processed data such as train.cpkl, test.cpkl.

**Comment by vamships** [comment]
Hi,
Here are the data files for the experiments listed in the paper: https://zenodo.org/record/3885236

**Comment by HantaoShu** [comment]
Thanks

**Comment by fslee62** [comment]
hello srivamshi,
i was learning about GCN and came across your paper. i find it to be highly relevant to what i am interested in. so i decided to try out PECAN. i am a beginner in NN. so my questions may reflect a lack of understanding in general.  here are a few initial questions:
1. as far as i can tell, the dataset (the 191 pro-pro complexes) for transfer learning is not included in the download from zenodo.org. did i miss something here or it is available somewhere?
2. the matrix dimensions inside the provided pickle files (e.g. train.cpkl) are different from what was described in the README file. for example, l_edge is 'numresx25' (cpkl) and 'numresx25x2' (readme). also, l_hood_indices is 'numresx30' (cpkl) and 'numresx25' (readme). did i misinterpret something?
3. my understanding is that i need to use the pro-pro dataset to run GCN_protein_base. only after that can i then run GCN_xTransfer, which uses output from GCN_protein_base. am i correct here? if so, don't i need to have access to the 191 pro-pro dataset? currently, the yml files inside GCN_protein_base use "train.cpkl" as input, which i don't understand.
4. thinking ahead, i like to be able to create my own pickle input files, which looks like a daunting task to me. is it possible that you provide more information on how to achieve that like a procedure and some auxiliary tools/programs. if not, any pointers here.

i know that is a handful. i sincerely appreciate your help and guidance. cheers.
