### ISSUE TITLE
Swapped primary and secondary sequences

### ISSUE THREAD

**Issue by minjunp** [vamships/PECAN#10]
Hi,

In your published dataset, I found primary sequences and secondary sequences are swapped in every other line of the dataset.
I was wondering what was the motivation for having repeated yet swapped sequences in the dataset.

This leads to twice as many complexes in the processed data.

**Comment by vamships** [comment]
Yes, the proteins are swapped in the dataset. In each Ab:Ag complex, the first protein gets to be _primary_ and the second protein _secondary_. In the swapped complex, the roles are reversed. The prediction is always on the primary protein, so if antigen is the _primary_, task is epitope prediction, and if the antibody is the _primary_, the task is paratope prediction.

**Comment by minjunp** [comment]
Thanks!
