### ISSUE TITLE
About "the 0.5 cutoff"

### ISSUE THREAD

**Issue by guoyanb** [vamships/PECAN#3]
In the paper "While our networks output a probability for each residue, to enable a direct comparison to other epitope and  paratope prediction methods we computed precision and recall by predicting as interface residues those with probability above 0.5" . However, the scores of " scores = self.get_predictions_loss(data, model, tt)[0]" has 
 some values above 1. Before computing precision, are the scores transformed into the probability using the sigmoid function? Next, the labels are '1' when the scores are above 0.5. The labels are '-1' when the scores are below 0.5 . 
Thanks a lot!

**Comment by vamships** [comment]
To convert the outputs to labels, we used the `get_predicted_label` function as defined below:
```
import numpy as np


def sigmoid(x):
    x_exp = np.exp(-x)
    return 1/(1+x_exp)

def get_predicted_label(scores):
    scores_probability = sigmoid(scores)
    return (scores_probability > 0.5) * 1
```
