### ISSUE TITLE
last residue of every protein in the input pickle files

### ISSUE THREAD

**Issue by fslee62** [vamships/PECAN#5]
i noticed the node features for the last residue of every primary or secondary protein are always "blank".  what is the purpose for that? thanks very much. fred

**Comment by vamships** [comment]
It is a dummy residue with no features. Since the graph convolution operator needs a fixed size neighborhood matrix, and not all residues are guaranteed to have so many neighbors, I used this dummy residue for [padding](http://d2l.ai/chapter_convolutional-neural-networks/padding-and-strides.html).
