### ISSUE TITLE
what is the best way to use existing weights from training to test new cases w/o doing the same training again?

### ISSUE THREAD

**Issue by fslee62** [vamships/PECAN#6]
i would like to run testing directly (using a new test.cpkl) without going through the same training and validation phases again. is there a convenient way to do that using the existing github code and yml files? if not, any pointers or advice on how i may want to achieve that? thanks again very much. fred

**Comment by vamships** [comment]
If I understand this correctly, you would like to use a model from a specific training run for testing on future data. To do this, you could save the model to a checkpoint and run it on your test data. It is not implemented in the code, but pointers to do so are [here](https://www.tensorflow.org/guide/checkpoint) and [here](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/keras/save_and_restore_models.ipynb).

**Comment by fslee62** [comment]
thanks much. you confirmed my cursory understanding of the code. those pointers were excellent indeed. thanks again.
