### ISSUE TITLE
Request for original dataset

### ISSUE THREAD

**Issue by bbjy** [vamships/PECAN#7]
Thank you for your code. I am very interested in this work, and I want to further understand it.

I want to know the residue sequence corresponding to the released dataset, however, the length of some of the ligand/receptor chains in this work  is not consistent with that of PDB file (I download the pdb file from https://www.rcsb.org/). So would you please share the original dataset (e.g. pdb file or residue sequence file) with me? Or perhaps you could suggest me how could I identify the original data in some way.

Thank you so much! Looking forward to your reply.

**Comment by vamships** [comment]
Hi @bbjy ,

The sequences for the two tasks are attached.
[sequences.zip](https://github.com/vamships/PECAN/files/7077605/sequences.zip)

**Comment by bbjy** [comment]
@vamships  Thank you so much! 
I checked the sequence, but I find that the sequence your provided of **antibody** (heavy chain + light chain) in **epitope folder** seems not consistent with the length of these in the **'.pkl' file** you provided in 'https://zenodo.org/record/3885236'. Is that so?

**Comment by vamships** [comment]
Yes, the antibody sequence used in the task corresponds to the 'CDR clouds' that we describe in section 2.A of the paper. You'd need to submit sequences to a CDR annotation tool like IMGT V-Quest, and then build the CDR clouds using the CDR annotations and PDB structures.

**Comment by bbjy** [comment]
> Yes, the antibody sequence used in the task corresponds to the 'CDR clouds' that we describe in section 2.A of the paper. You'd need to submit sequences to a CDR annotation tool like IMGT V-Quest, and then build the CDR clouds using the CDR annotations and PDB structures.

I got it. Thanks a lot!
